using Ldp.Project;

namespace Ldp.EngineProbe;

/// <summary>
/// Exact-argument checks for the still-image → .m2v builder. The two reference
/// commands are the author's own tested ones, and the frame counts are checked
/// against real files they generated by hand (a 5 s banner came out 120 frames,
/// a 6.5 s passage 156, a 2 s one 48) so the app can never quietly drift from
/// what a hand-run FFmpeg produces.
/// </summary>
public static class StillImageTest
{
    public static void Run(Action<string, bool> Check)
    {
        const double film = 24000.0 / 1001.0; // 23.976
        string image = @"C:\art\Hypseus_Singe_instructions.png";
        string output = @"C:\game\Video\output.m2v";

        // ---- The plain reference command ----
        // ffmpeg -loop 1 -i "…png" -t 5 -r 24000/1001 -vf "scale=1600:900"
        //        -c:v mpeg2video -q:v 2 -f mpeg2video output.m2v
        var plain = new StillOptions { Seconds = 5, Width = 1600, Height = 900, Fps = film };
        Check("still: plain command args exact", StillImage.BuildArgs(image, output, plain).SequenceEqual(
        [
            "-y", "-loop", "1", "-framerate", "24000/1001", "-i", image,
            "-t", "5", "-r", "24000/1001",
            "-vf", "scale=1600:900", "-c:v", "mpeg2video", "-q:v", "2",
            "-f", "mpeg2video", output,
        ]));

        // The image demuxer defaults to 25 fps, so an unpinned input computes the
        // filters at 25 and rate-converts. Measured against real FFmpeg: that put
        // the end of a 0.5 s fade-in on frame 13 instead of the requested 12.
        IReadOnlyList<string> plainArgs = StillImage.BuildArgs(image, output, plain);
        int inputRate = plainArgs.ToList().IndexOf("-framerate");
        int outputRate = plainArgs.ToList().LastIndexOf("-r");
        Check("still: input frame rate is pinned before -i",
              inputRate >= 0 && inputRate < plainArgs.ToList().IndexOf("-i"));
        Check("still: input and output rates are the same value",
              plainArgs[inputRate + 1] == plainArgs[outputRate + 1]);

        // ---- The fade reference command ----
        // -t 6.5 … -vf "scale=1600:900,fade=t=in:st=0:d=0.5,fade=t=out:st=6.0:d=0.5"
        var faded = new StillOptions
        {
            Seconds = 6.5, Width = 1600, Height = 900, Fps = film,
            Fade = true, FadeInSeconds = 0.5, FadeOutSeconds = 0.5,
        };
        Check("still: fade filter matches the reference",
              StillImage.BuildFilter(faded) == "scale=1600:900,fade=t=in:st=0:d=0.5,fade=t=out:st=6:d=0.5");
        Check("still: fade command args exact", StillImage.BuildArgs(image, output, faded).SequenceEqual(
        [
            "-y", "-loop", "1", "-framerate", "24000/1001", "-i", image,
            "-t", "6.5", "-r", "24000/1001",
            "-vf", "scale=1600:900,fade=t=in:st=0:d=0.5,fade=t=out:st=6:d=0.5",
            "-c:v", "mpeg2video", "-q:v", "2", "-f", "mpeg2video", output,
        ]));

        // ---- Frame counts, checked against files the author generated by hand ----
        Check("still: 5s at 23.976 is 120 frames", StillImage.FrameCount(5, film) == 120);
        Check("still: 6.5s at 23.976 is 156 frames", StillImage.FrameCount(6.5, film) == 156);
        Check("still: 2s at 23.976 is 48 frames", StillImage.FrameCount(2, film) == 48);
        // A whole number of frames must NOT round up to one extra.
        Check("still: 5s at 24 is exactly 120 frames", StillImage.FrameCount(5, 24) == 120);
        Check("still: 10s at 30 is exactly 300 frames", StillImage.FrameCount(10, 30) == 300);
        Check("still: zero length is zero frames", StillImage.FrameCount(0, film) == 0);

        // ---- MPEG-2 legal rates ----
        // The standard stores the rate as a 4-bit code: anything else silently
        // becomes the nearest legal rate and the game's frame timing drifts.
        Check("still: 23.976 snaps to 24000/1001", StillImage.NearestRate(23.976).Rational == "24000/1001");
        Check("still: 29.97 snaps to 30000/1001", StillImage.NearestRate(29.97).Rational == "30000/1001");
        Check("still: 30 stays 30", StillImage.NearestRate(30).Rational == "30");
        Check("still: 25 stays 25", StillImage.NearestRate(25).Rational == "25");
        Check("still: 59.94 snaps to 60000/1001", StillImage.NearestRate(59.94).Rational == "60000/1001");
        Check("still: 23.976 is a legal rate", StillImage.IsLegalRate(23.976));
        Check("still: 23.976023976 is a legal rate", StillImage.IsLegalRate(film));
        Check("still: 15 fps is not a legal rate", !StillImage.IsLegalRate(15));
        Check("still: every listed rate is legal",
              StillImage.Mpeg2Rates.All(r => StillImage.IsLegalRate(r.Fps)));
        Check("still: illegal rate is reported, not silently used",
              StillImage.Validate(new StillOptions { Seconds = 5, Width = 640, Height = 480, Fps = 15 })
                        .Any(p => p.Contains("not an MPEG-2 frame rate")));

        // ---- Fit ----
        var pad = new StillOptions { Seconds = 5, Width = 1600, Height = 900, Fps = film, Fit = StillFit.Pad };
        Check("still: pad keeps the artwork's proportions", StillImage.BuildFilter(pad) ==
              "scale=1600:900:force_original_aspect_ratio=decrease,pad=1600:900:(ow-iw)/2:(oh-ih)/2");
        Check("still: stretch is a bare scale", StillImage.BuildFilter(plain) == "scale=1600:900");

        // ---- Fade edge cases ----
        var noIn = new StillOptions
        {
            Seconds = 4, Width = 640, Height = 480, Fps = film,
            Fade = true, FadeInSeconds = 0, FadeOutSeconds = 1,
        };
        Check("still: a zero fade-in emits no fade=in clause", !StillImage.BuildFilter(noIn).Contains("t=in"));
        Check("still: fade-out start is length minus its duration",
              StillImage.BuildFilter(noIn).Contains("fade=t=out:st=3:d=1"));

        // A fade-out longer than the passage would start before frame zero.
        var overrun = new StillOptions
        {
            Seconds = 1, Width = 640, Height = 480, Fps = film,
            Fade = true, FadeInSeconds = 0, FadeOutSeconds = 4,
        };
        Check("still: an over-long fade-out clamps to zero, never negative",
              StillImage.BuildFilter(overrun).Contains("st=0:"));

        Check("still: fades longer than the passage are reported",
              StillImage.Validate(new StillOptions
              {
                  Seconds = 1, Width = 640, Height = 480, Fps = film,
                  Fade = true, FadeInSeconds = 1, FadeOutSeconds = 1,
              }).Any(p => p.Contains("never reaches full brightness")));

        Check("still: no fade means no fade filter at all", !StillImage.BuildFilter(plain).Contains("fade"));

        // ---- Fade boundary, measured against real FFmpeg ----
        // Decoding the reference passage frame by frame put mean brightness at
        // 35.088 on frame 11 and 38.377 (full) on frame 12 — but only with the
        // input rate pinned. Unpinned it was still 92% lit at frame 12.
        Check("still: without a fade the first frame is already visible",
              plain.FirstFullyVisibleFrame == 0);
        Check("still: a 0.5s fade-in at 23.976 clears after 12 frames",
              faded.FirstFullyVisibleFrame == 12);

        // ---- The frame a still slot points at ----
        // A single-frame slot freezes on one frame, so it only needs one that is
        // certainly at full brightness. The midpoint is, whatever the fades do,
        // and it does not depend on FFmpeg's fade rounding.
        Check("still: the slot frame is the middle of the passage", faded.MidFrame == 78);
        Check("still: the slot frame clears the fade-in by a wide margin",
              faded.MidFrame > faded.FirstFullyVisibleFrame);
        Check("still: the slot frame clears the fade-out too",
              faded.MidFrame < StillImage.FrameCount(faded.Seconds - faded.FadeOutSeconds, faded.Fps));
        Check("still: a plain 5s passage puts the slot frame at 60", plain.MidFrame == 60);
        // Longest fades Validate still permits: the midpoint must remain lit.
        var tight = new StillOptions
        {
            Seconds = 4, Width = 640, Height = 480, Fps = film,
            Fade = true, FadeInSeconds = 2, FadeOutSeconds = 2,
        };
        Check("still: even with back-to-back fades the midpoint is not inside the fade-in",
              tight.MidFrame >= tight.FirstFullyVisibleFrame);

        // ---- Validation ----
        Check("still: zero length is rejected",
              StillImage.Validate(new StillOptions { Seconds = 0, Width = 640, Height = 480, Fps = film })
                        .Any(p => p.Contains("more than zero")));
        Check("still: an odd dimension is rejected (MPEG-2 needs even)",
              StillImage.Validate(new StillOptions { Seconds = 5, Width = 641, Height = 480, Fps = film })
                        .Any(p => p.Contains("odd side")));
        Check("still: a sound setup validates clean", StillImage.Validate(plain).Count == 0);
        Check("still: the faded reference validates clean", StillImage.Validate(faded).Count == 0);

        // ---- Output naming ----
        Check("still: output is named after the image",
              StillImage.SuggestOutputName(@"C:\art\EggmansLaserForge_banner.png") == "EggmansLaserForge_banner.m2v");
        Check("still: spaces become underscores in the name",
              StillImage.SuggestOutputName(@"C:\art\game controls.png") == "game_controls.m2v");
        Check("still: a jpg still yields an .m2v name",
              StillImage.SuggestOutputName(@"C:\art\title.jpg") == "title.m2v");

        // ---- Accepted inputs ----
        Check("still: png is an image", StillImage.IsImage("a.PNG"));
        Check("still: jpg is an image", StillImage.IsImage("a.jpg"));
        Check("still: m2v is not an image", !StillImage.IsImage("a.m2v"));
        Check("still: mkv is not an image", !StillImage.IsImage("a.mkv"));
    }
}
